# Assignment 1: NumPy Part 1


## Learning Objectives
This lesson meets the following learning objectives:

- The ability to use Python data structures provided in NumPy.

## Instructions
Read through all of the text in this page. This assignment provides step-by-step training divided into numbered sections. The sections often contain embeded exectable code for demonstration.  Section headers with icons have special meanings:  

- <i class="fas fa-puzzle-piece"></i> The puzzle icon indicates that the section provides a practice exercise that must be completed.  Follow the instructions for the exercise and do what it asks.  Exercises must be turned in for credit.
- <i class="fa fa-cogs"></i> The cogs icon indicates that the section provides a task to perform.  Follow the instructions to complete the task.  Tasks are not turned in for credit but must be completed to continue progress.

Review the list of items in the **Expected Outcomes** section to check that you feel comfortable with the material you just learned. If you do not, then take some time to re-review that material again. If after re-review you are not comfortable, do not feel confident or do not understand the material, please ask questions on Slack to help.

Follow the instructions in the **What to turn in** section to turn in the exercises of the assginment for course credit.

## Background
This notebook is based on the official `NumPy` [documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html).  Unless otherwise credited, quoted text comes from this document.  The Numpy documention describes NumPy in the following way:

> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> - a powerful N-dimensional array object
> - sophisticated (broadcasting) functions
> - tools for integrating C/C++ and Fortran code
> - useful linear algebra, Fourier transform, and random number capabilities
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


In [ ]:
Questions:
    1.Can initalized arrays like arrange np.arange((4,8,5)) be given a shape? or are they only a 1D single array?
    2.  How would we take a row from our array and sum it?
    3. 5.2 practice Line 25, why is the matching pair false? I predicted it should be true
                    Line 32

## <i class="fa fa-cogs"></i> Notebook Setup
First, we must import the NumPy library.  All packages are imported at the top of the notebook. Execute the code in the following cell to get started with this notebook (type Ctrl+Enter in the cell below)

In [2]:
# Import numpy
import numpy as np

The code above imports numpy as a variable named `np`. We can use this variables to access the functionality of NumPy.  The above is what we will use for the rest of this class.

You may be wondering why we didn't import numpy like this:  
```python
import numpy
```
We could, but the first is far more commonly seen, and allows us to the `np` variable to access the functions and variables of the NumPy package. This makes the code more readable because it is not a mystery where the functions come from that we are using.

## 1. The NumPy Array
### 1.1. Learning
What is an array?  An array is a data structure that stores one or more objects of the same type (e.g. integers, strings, etc.) and can be multi-dimensional (e.g. 2D matricies). In python, the list data type provides this type of functionality, however, it lacks important operations that make it useful for scientific computing.  Therefore, NumPy is a Python package that defines N-dimensional arrays and provides support for linear algebra, and other fucntions useful to scientific computing.

From the Numpy QuickStart Tutorial: 
> NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. 

<div class="alert alert-warning">
    <b>Note</b>:  a "tuple" is a list of numbers. For example, the pair of numbers surrounded by parentheses: (2,4), is a tuple containing two numbers.
</div>

NumPy arrays can be visualized in the following way:

<img src="./media/A01-content_arrays-axes.png">

(image source: https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

Using built-in Python lists, arrays are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = [1,2,3]  

# A 2-dimensional list of numbers.
my_2d_array = [[1,2,3],[4,5,6]]

# A 3-dimensional list of numbers.
my_3d_array = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]

# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

```

Using NumPy, arrays are created using the `np.array()` function. For example, arrays with the same contents as above are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = np.array([1,2,3,4])

# A 2-dimensional list of numbers.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])

# A 3-dimensional list of numbers.
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])

# Two lists of boolean values
a = np.array([True,True,False,False])
b = np.array([False,False,True,True])
```

In NumPy, these arrays are an object of type `ndarray`.  You can learn more about the `ndarray` class on the [NumPy ndarray introduction page](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html). However, this tutorial will walk you through some of the most important attributes, functions and uses of NumPy.

### 1.2. <i class="fas fa-puzzle-piece"></i> Practice

Perform the following in the cell below.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [19]:
array1 = np.array([2,5,3,6])
print("1D array", array1)
array2 = np.array([[2,5,3,6], [4,4,5,6]])
print("2D array", array2) 
array3 = np.array([[[2,5,3,6], [4,4,5,6]], [[7,4,1,5], [8,5,2,6]]])
print("3D array", array3) 

1D array [2 5 3 6]
2D array [[2 5 3 6]
 [4 4 5 6]]
3D array [[[2 5 3 6]
  [4 4 5 6]]

 [[7 4 1 5]
  [8 5 2 6]]]


## 2. Array Attributes
### 2.1. Learning 
For this section we will retrieve information about the arrays. Once an array is created you can access information about the array such as the number of dimensions, its shape, its size, the data type that it stores, and the number of bytes it is consuming. There are a variety of attributes you can use such as:
+ `ndim`
+ `shape`
+ `size`
+ `dtype`
+ `itemsize`
+ `data`
+ `nbytes`

For example, to get the number of dimensions for an array:
```Python
# Print the number of dimensions for the array:
print(my_3d_array.ndim)
```

You can learn more about these attributes, and others from the [NumPy ndarray reference page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) if you need help understanding the attributes.

Notice that we use dot notation to access these attributes, yet we do not provide the parenthesis `()` like we would for a function call.  This is because we are accessing attributes (i.e. member variables) of the numpy object, we are not calling a function

### 2.1. <i class="fas fa-puzzle-piece"></i> Practice



In the cell below, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [43]:
#prints origional array
print(array3)
#prints the number of dimensions (3D)
print(array3.ndim)
#prints the shape: , 2 block groups, of 2 blocks each, with a string length of 4
print(array3.shape)
#print the size of array (number of characters)
print(array3.size)
#print the type of array, int that stores the number either 32 or 64, 8 bits in a byte, in a 8bytes in 64 bits, a byte is either a 0 or 1
print(array3.dtype)
#prints the item size: length of one array
print(array3.itemsize)
print(array2.itemsize)
#prints data  location memory is stored
print(array3.data)
#prints nbytes that the array uses                        ???
print(array3.nbytes)

[[[2 5 3 6]
  [4 4 5 6]]

 [[7 4 1 5]
  [8 5 2 6]]]
3
(2, 2, 4)
16
int32
4
4
64


## 3. Creating Initialized Arrays
### 3.1. Learning

Here we will learn to create initialized arrays. These arrays are pre-initalized with default values.  NumPy provides a variety of functions for creating and intializing an array in easy-to-use functions. Some of these include: 

+ [np.ones()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones): Returns a new array of given shape and type, filled with ones.
+ [np.zeroes()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros): Returns a new array of given shape and type, filled with zeros.
+ [np.empty()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty): Return a new array of given shape and type, without initializing entries.
+ [np.full()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full): Returns a new array of given shape and type, filled with a given fill value.
+ [np.arange()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html#numpy.arange): Returns a new array of evenly spaced values within a given interval.
+ [np.linspace()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html#numpy.linspace): Returns a new array of evenly spaced numbers over a specified interval.
+ [np.random.random](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.random.html): Can be used to return a single random value or an array of random values between 0 and 1.

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output (i.e array) it generates.

NumPy has a large list of array creation functions, you can learn more about these functions on the [array creation routins page](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html) of the NumPy documentation. 

To demonstrate the use of these functions, the following code will create a two-dimensional array with 3 rows and 4 columns (i.e 3 *x* 4) filled with 0's.  

```Python
zeros = np.zeros((3, 4))
```

The following creates a 1D array of values between 3 and 7

```Python
np.arange(3, 7)
```
The result is: `array([3, 4, 5, 6])`

The following creates a 1D array of values between 0 and 10 spaced every 2 integers:

```Python
np.arange(0, 10, 2)
```
The result is: `array([0, 2, 4, 6, 8])`

Notice that just like with Python list slicing, the range uncludes up-to, but not including the "stop" value of the range.


### 3.1. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [59]:
#prints a 2D array with ones
ones = np.ones((3,3))
print(ones)
#prints a 3D array with zeros
zeros = np.zeros((4,4,4)) 
print(zeros)
#print an empty array in a string of length = 3, this will fill with the last numbers used
empty = np.empty(3)
print(empty)
#print arranged array between 3 and 19 in increments by 3 (WHY CAN THE START VALUE BE INCLUDED BUT THE ENDING VALUE IS NOT (IF i 
# CHANGED THE END TO 18, IT IS NOT INCLUDED)
arranged = np.arange(3,19,3)
print(arranged)
# Print linspace min value is 3 max value is 19, 5 numbers evenly spaced (in this case is 4 digits apart from one another)
linspace = np.linspace(3,19,5)
print(linspace)
#print a random 3D array that is two arrays wide, 4 arrays tall, and has a string lengtth of 6
random = np.random.random((2,4,6))
print(random)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1.27319747e-313 2.54639495e-313 3.81959242e-313]
[ 3  6  9 12 15 18]
[ 3.  7. 11. 15. 19.]
[[[0.71950575 0.99249972 0.11982328 0.60710574 0.8232414  0.952707  ]
  [0.34008608 0.0088612  0.61018064 0.44242554 0.90270719 0.26006508]
  [0.66471681 0.07355788 0.92774619 0.34681822 0.96525087 0.96598983]
  [0.87500062 0.63152291 0.91881339 0.19469205 0.89757985 0.48339224]]

 [[0.21193026 0.51824305 0.51954634 0.31539492 0.66872748 0.46810269]
  [0.85809124 0.33366137 0.31394057 0.43467945 0.2364875  0.24103987]
  [0.28133847 0.72638137 0.23789959 0.14697436 0.32951107 0.25423269]
  [0.52623789 0.86706087 0.66047347 0.53325155 0.9902675  0.66103241]]]


## 4. Performing Math and Broadcasting
### 4.1. Learning

At times you may want to apply mathematical operations between arrays. For example, suppose you wanted to add, multiply or divide the contents of two arrays.  If the two arrays are the same size this is straightfoward. However if the arrays are not the same size then it is more challenging.  This is where Broadcasting comes to play:

> The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. (https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)


#### 4.1.1. Arrays of the same size
To demonstrate math with arrays of the same size, the following cell contains code that creates two arrays of the exact same size: _3 x 4_.  Execute the cell to create those arrays:

In [3]:
# Define demo arrays:
demo_a = np.ones((3,4))
demo_b = np.random.random((3,4))

# Print the shapes of each array.
print(f"demo_a shape: {demo_a.shape}")
print(f"demo_b Shape: {demo_b.shape}")

demo_a shape: (3, 4)
demo_b Shape: (3, 4)


Let's print the array to see what they contain:

In [4]:
print(demo_a)
print(demo_b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.69799204 0.26911871 0.80953264 0.51463135]
 [0.48453414 0.77120439 0.50636748 0.71153239]
 [0.70613757 0.86232    0.75668815 0.37292801]]


Because these arrays are the same size we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [62]:
# These arrays have the same shape, 
demo_a + demo_b

array([[1.91103287, 1.56619473, 1.72699461, 1.78611096],
       [1.24336926, 1.60345839, 1.6931009 , 1.18318456],
       [1.23449768, 1.16625897, 1.66272342, 1.10902613]])

The addition resulted in the corresponding positions in each matrix being added to the other and creating a new matrix.  If you need clarification for how two matricies can be added or subtracted see the [Purple Math](https://www.purplemath.com/modules/mtrxadd.htm) site for examples.

#### 4.1.2. Broadcasting for Arrays of Different Sizes
When arrays are not the same size, you cannot perform simple math.  For this, NumPy provides a service known as "broadcasting". To broadcast, NumPy automatically resizes the arrays to match, and fills in newly created empty cells with values.

To Broadcast, NumPy begins at the right-most dimensions of the array and comparses them then moves left and compares the next set. As long as each set meet the following criteria, Broadcasting can be performed:

+  The dimensions are equal or
+  One of the dimensions is 1.

Consider two arrays of the following dimensions:

+ 4D array 1:  10 x 1 x 3 x 1
+ 3D array 2:       2 x 1 x 9

These arrays are not the same size, but they are compatible with broadcasting because at each diemsion (from right to left) the dimension crtieria is met. When performing math, the value in each dimension of size 1 is broadcast to fill that dimesion (an example is provided below). The resulting array, if the above arrays are added, will be broadcasted to a size of _10 x 2 x 3 x 9_

To demonstrate math with arrays of different size, the following cell contains code that creates two arrays: one of size _3 x 4_ and onther of size _4 x 1_.  Execute the cell to create those arrays:

In [68]:
# Create the arrays.
demo_c = np.ones((3,4))
demo_d = np.arange(4)

# Print the array shapes.
print(f"demo_c shape: {demo_c.shape}")
print(f"demo_d Shape: {demo_d.shape}")

demo_c shape: (3, 4)
demo_d Shape: (4,)


Let's print the array to see what they contain:

In [66]:
print(demo_c)
print(demo_d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


Because these arrays meet our brodcasting requirements, we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [69]:
demo_c + demo_d

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

The addition resulted in the value in each dimension of size 1, being "broadcast" or "streched" throughout that dimesion and then used in the operation. 

#### 4.1.3. Broadcasting With Higher Dimensions

Consider the following arrays of 2 and 3 dimensions. 

In [5]:
demo_e = np.ones((3, 4))
demo_f = np.random.random((5, 1, 4))
print(f"demo_e shape: {demo_e.shape}")
print(f"demo_f shape: {demo_f.shape}")

demo_e shape: (3, 4)
demo_f shape: (5, 1, 4)


Print the arrays to see what they contain:

In [6]:
print(demo_e)
print(demo_f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[3.43510203e-01 5.06715180e-01 2.60965850e-01 6.15917725e-01]]

 [[4.86050856e-01 1.16826927e-01 6.60276072e-01 4.32309863e-01]]

 [[5.38309197e-01 1.27093479e-01 6.33540581e-04 3.98672326e-01]]

 [[6.90497106e-01 9.92679238e-01 6.74194393e-01 5.72379590e-01]]

 [[1.27954222e-01 7.68002011e-01 1.06504566e-02 1.86205481e-01]]]


These two arrays meet the rules for broadcasting becuase they both have a 4 in their last dimension and there is a 1 in the  `demo_f` 2nd dimension.  

Perform the math by executing the following cell:

In [7]:
result = demo_e + demo_f
print(result)

[[[1.3435102  1.50671518 1.26096585 1.61591773]
  [1.3435102  1.50671518 1.26096585 1.61591773]
  [1.3435102  1.50671518 1.26096585 1.61591773]]

 [[1.48605086 1.11682693 1.66027607 1.43230986]
  [1.48605086 1.11682693 1.66027607 1.43230986]
  [1.48605086 1.11682693 1.66027607 1.43230986]]

 [[1.5383092  1.12709348 1.00063354 1.39867233]
  [1.5383092  1.12709348 1.00063354 1.39867233]
  [1.5383092  1.12709348 1.00063354 1.39867233]]

 [[1.69049711 1.99267924 1.67419439 1.57237959]
  [1.69049711 1.99267924 1.67419439 1.57237959]
  [1.69049711 1.99267924 1.67419439 1.57237959]]

 [[1.12795422 1.76800201 1.01065046 1.18620548]
  [1.12795422 1.76800201 1.01065046 1.18620548]
  [1.12795422 1.76800201 1.01065046 1.18620548]]]


The resulting array has dimensions of _5 x 3 x 4_.  For this math to work, the values from `demo_f` had to be "stretched" (i.e. copied and then added) in the second dimension

### 4.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [17]:
array = np.random.random((8,2,6))
array1 = np.zeros((2,6))
print(f"array1: {array.shape}")
print(f"array: {array1.shape}")

print(f" array + array1 = {array + array1}")

array1: (8, 2, 6)
array: (2, 6)
 array + array1 = [[[0.51200503 0.06136566 0.46344686 0.09997306 0.98779572 0.8326105 ]
  [0.19640621 0.36303316 0.27640901 0.38277805 0.73543814 0.4305805 ]]

 [[0.53156569 0.86183126 0.88563425 0.47648053 0.32210848 0.76526543]
  [0.91858818 0.79104799 0.22930416 0.54031521 0.22972061 0.96972101]]

 [[0.13078889 0.24694851 0.22310183 0.05817129 0.0143511  0.45362412]
  [0.78830599 0.64565048 0.88071627 0.26374022 0.47325876 0.99882526]]

 [[0.96489404 0.44869936 0.48609794 0.51755626 0.06730617 0.31808852]
  [0.51199484 0.54882058 0.36312737 0.44420852 0.34991119 0.00637008]]

 [[0.63951151 0.48900826 0.52808822 0.50088501 0.86902024 0.57433811]
  [0.33092334 0.66182325 0.33355891 0.08965893 0.30127999 0.47024954]]

 [[0.57557192 0.58178695 0.88579592 0.43610492 0.72829675 0.23219365]
  [0.04462688 0.13307806 0.31650753 0.94646047 0.97562856 0.92857087]]

 [[0.27508644 0.15833401 0.0723264  0.21830864 0.06664556 0.171001  ]
  [0.08222109 0.1503564  0.8

## 5. NumPy Aggregate Functions
### 5.1. Learning

NumPy also provides a variety of functions that "aggregate" data. Examples of aggreagation of data include calculating the sum of every element in the array, calculating the mean, standard deviation, etc.  Below are a few examples of aggregation functions provided by NumPy.

#### 5.1.1 Mathematical Functions
+ [np.sum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html): sums the array elements over a given axis
+ [np.minimum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html#numpy.minimum): compares two arrays and returns a new array of the minimum at each position (i.e. element-wise)
+ [np.maximum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html#numpy.maximum): compares two arrays and returns a new array of the maximum at each position (i.e. element-wise).
+ [np.cumsum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html#numpy.cumsum): returns the cummulative sum of the elements along a given axes.

You can find more about mathematical functions for arrays at the [Numpy mathematical functions page](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

#### 5.1.2 Statistics
+ [np.mean()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html): compute the arithmetic mean along the specified axis.
 [np.median()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html#numpy.median): compute the median along the specified axis.
+ [np.corrcoef()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy.corrcoef): return Pearson product-moment correlation coefficients between two 1D arrays or one 2D array.
+ [np.std()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html#numpy.std): compute the standard deviation along the specified axis.
+ [np.var()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html#numpy.var): compute the variance along the specified axis.

You can find more about statistical functions for arrays at the [Numpy statistical functions page](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html).


Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

For example:
```Python
# Calculate the sum of our demo data from above
np.sum(demo_e)
```


In [21]:
sums = np.sum(demo_e)
sums


12.0

#### 5.1.3 Logical Aggregate Functions
When arrays contain boolean values there are additional logical aggregation functions you can use: 

 + [logical_and()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html#numpy.logical_and): computes the element-wise truth value of two arrays using AND.
 + [logical_or()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_or.html#numpy.logical_or): computes the element-wise truth value of two arrays using OR.
 + [logical_not()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html#numpy.logical_not):  computes the element-wise truth value of two arrays using NOT.
 
 
You can find more about logical functions for arrays at the [Numpy Logic functions page](https://docs.scipy.org/doc/numpy/reference/routines.logic.html).

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

To demonstrate usage of the logical functions, please execute the following cells and examine the results produced.

### 5.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  

In [37]:
# Two lists of boolean values- truth test, based on if it is true or not
a = [True, True, False, False]
b = [False, False, True, False]

# Perform a logical "or": if True or False in in these positions it will be TRUE, if it is a matching pair it will be false
#Seems like if it matches then it writes the match (True or False), and if it dosn't then it is False,- which dosn't seem to help Id the true 
#falses.
np.logical_or(a, b)

array([ True,  True,  True, False])

In [42]:
# Perform a logical "and": I predict it will be array([False, False, False, True])
np.logical_and(a, b)

array([False, False, False, False])

### 5.3. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  

In [41]:
array = [True, False, True, True]
array1 = [False, False, False, True]

#logical_and, I predict that it should give array([False, True, False, True])- 
And = np.logical_and(array, array1)
print(And)
#Logial_or, I predict that it will give array([True,False, True, False])- why does it print the last True if they match??
Or = np.logical_or(array, array1)
print(Or)

[False False False  True]
[ True False  True  True]


## Expected Outcomes
At this point, you should feel comfortable with the following:
 - What is a NumPy array
 - Using NumPy array attributes 
 - Performing broadcasting
 - Using aggregate functions


## What to Turn in?
Be sure to **commit** and **push** your changes to this notebook.  All practice exercises should be completed.  Once completed, send a **Slack message** to the instructor indicating you have completed this assignment. The instructor will verify all work is completed. 