# Assignment 2: NumPy Part 2

## Learning Objectives
This lesson meets the following learning objectives:

- The ability to use Python data structures provided in NumPy.

## Instructions
Read through all of the text in this page. This assignment provides step-by-step training divided into numbered sections. The sections often contain embeded exectable code for demonstration.  Section headers with icons have special meanings:  

- <i class="fas fa-puzzle-piece"></i> The puzzle icon indicates that the section provides a practice exercise that must be completed.  Follow the instructions for the exercise and do what it asks.  Exercises must be turned in for credit.
- <i class="fa fa-cogs"></i> The cogs icon indicates that the section provides a task to perform.  Follow the instructions to complete the task.  Tasks are not turned in for credit but must be completed to continue progress.

Review the list of items in the **Expected Outcomes** section to check that you feel comfortable with the material you just learned. If you do not, then take some time to re-review that material again. If after re-review you are not comfortable, do not feel confident or do not understand the material, please ask questions on Slack to help.

Follow the instructions in the **What to turn in** section to turn in the exercises of the assginment for course credit.

In [ ]:
QUESTIONS:
    1.1 Is there a visual aid that go with the negative indexing? I am not understanding the -1, -1
    1.2 practice why does arrary[1] print the middle dimension. How would you get it to print the first?
    2.2 practice AND/ OR combinations with booleans
    2.3 demo_f[[0,100,200,300,400]] how do these numbers arrange the output
    3.0 help(), I had an error that said to try to use a.all() and I tried to get help by using help(a.all) and help(a.all()) and got errors
    4.6 [line39] eaiser to take package.function, but struggling with variable.fuction see comments 

## <i class="fa fa-cogs"></i> Notebook Setup
First, we must import the NumPy library. 

In [2]:
# Import numpy
import numpy as np

## 1. Basic Indexing: Subsets and Slicing
### 1.1. Learning

We often want to consider a subset of a given array. You will recognize basic subsetting as it is similar to indexing of Python lists.  

The following code examples demonstrate how to subset a NumPy array:

```python
# Get items from "start" to "end" (but the end is not included!)
a[start:end] 

# Get all items from "start" through the rest of the array
a[start:]    

# Get items from the beginning to "end" (but the end is not included!)
a[:end]      
```
Similarly to Python lists, retriving elements from the end of a NumPy array uses negative indexing.  Execute the example code below to see a demonstration:

In [2]:
# Create a 5 x 2 array of random numbers
demo_g = np.random.random((5,2))
print(demo_g)

# Get the last item from the last 'row':
demo_g[-1, -1]

[[0.69695546 0.99144583]
 [0.23784465 0.72806599]
 [0.93862157 0.70650226]
 [0.81210515 0.4234351 ]
 [0.84434485 0.33779564]]


0.33779564387281924

### 1.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [44]:
array1  = np.random.random((3,2,1))
print(f"this is the original array: \n {array1} \n")

#PRINTS THE LAST ROW, COLUMN, VALUE
last1 = array1[-1,-1,-1]
print(f"this is the last digit: \n {last1} \n")

#Prints the last dimension
dim1 = array1[-1]
print(f"this is the last dim: \n {dim1} \n")

#prints a subset of the dimension
sub1 = array1[1]
print(f"this prints the first dim: \n {sub1} \n")



this is the original array: 
 [[[0.45665623]
  [0.46631932]]

 [[0.11580355]
  [0.47664259]]

 [[0.23051313]
  [0.1026107 ]]] 

this is the last digit: 
 0.10261070145504281 

this is the last dim: 
 [[0.23051313]
 [0.1026107 ]] 

this prints the first dim: 
 [[0.11580355]
 [0.47664259]] 



## 2. "Fancy" Indexing

Fancy indexing allows you to provide an array of indicies or an array of boolean values in order to subset an array.


### 2.1 Using a Boolean Array for Indexing
Rather than using an index range, as shown in the previous section, we can provide an array of boolean values where `True` indicates that we want the value in the position where `True` is found, and `False` indicates we do not want it.  Creating these boolean arrays is simple if we use conditional statements. 

For example, review and then execute the following code:

In [50]:
# Create a 5 x 2 array of random numbers
demo_g = np.random.random((5,2))
print(f" demo_g: \n {demo_g} \n")

# Find all values in the matrix less than 0.5
demo_g < 0.5

 demo_g: 
 [[0.41975839 0.19648065]
 [0.46732178 0.46271813]
 [0.71677263 0.02414079]
 [0.87559885 0.11091526]
 [0.67044891 0.93349083]] 



array([[ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False, False]])

Notice the return value is an array of boolean values.  True indicates if the value was less than 0.5. False indicates it is greater or equal. We can use this boolean array as an index for the same array to return only those values satisfy the boolean condition. Try executing the following code:

In [51]:
demo_g[demo_g < 0.5]

array([0.41975839, 0.19648065, 0.46732178, 0.46271813, 0.02414079,
       0.11091526])

Or alternatively:

In [52]:
sig_list = demo_g < 0.5
demo_g[sig_list]

array([0.41975839, 0.19648065, 0.46732178, 0.46271813, 0.02414079,
       0.11091526])

### 2.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [79]:
a1 = np.arange(15).reshape(3,5)
print(f"original: \n {a1} \n")

top = a1[a1 > 5]
print(f"greater than 5: \n {top} \n")
less = a1[a1 < 3]
print(f"less than 3: \n {less} \n")
equal = a1[a1 ==10]
print(f"is ten: \n {equal} \n")

OR = a1[a1 < 3]
OR1 = a1[a1 > 10]
comb = np.logical_and(OR, OR1)
print(f"less than 3, greater than 10: \n {comb} \n")



original: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

greater than 5: 
 [ 6  7  8  9 10 11 12 13 14] 

less than 3: 
 [0 1 2] 

is ten: 
 [10] 



ValueError: operands could not be broadcast together with shapes (3,) (4,) 

### 2.3 Using exact indicies

Alternatively, if there are specific elements from the array that we want to retrieve we can provide the specific numeric indices.  

For example, review and then execute the following code:

In [83]:
# Generate a list of 500 random numbers
demo_f = np.random.random((500))

# Retreive 5 random numbers from the list
demo_f[[0,100,200,300,400]]

array([0.11398212, 0.50908499, 0.16164569, 0.81315504, 0.96985055])

## 3. Intermission -- Getting Help

Python has a built in function, `help()`, we can call on any object (anything) to find out more about it. As we move deeper into the functions provided by most packages, we often need to know exactly what a given function expects as arguments.

The output of these `help()` calls can be long. Try executing the following help call for the `np.array` attribute:

In [87]:
# Call help on anything from a package.
#help(np.array)

Additionally, we can get help about an object that we created! Execute the following code to try it out:

In [85]:
# Call help on an object we created.
x = np.array([1, 2, 3, 4])
#help(x)

### 3.1 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [91]:
help(np.delete)
#delete function calls for an array or object/slice with no axis selected

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [40]:
help(.a.all)
#had an error suggestion to use this. But couldn't find it in the documentation.


AttributeError: module 'numpy' has no attribute 'a'

In [88]:
help(np.transpose)
# it describes you must have an array, and default no axes, should output an ndarray, then gives other functions potentially could be used

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the

## 4. Manipulating Arrays
Thus far, we have larned to create arrays, perform basic math, aggregate values, and index arrays. Finally, we need to learn to manipulate them by transposing, reshaping, splitting, joining appending, and deleting arrays.

### 4.1 Transposing
Transposing an array is equivalent to flipping it both horizontally and vertically as shown in the following animated image:

<img src="./media/A01-Matrix_transpose.gif">

(image source: https://en.wikipedia.org/wiki/Transpose)

Numpy allows you to tranpose a matrix in one of two ways:

+ Using the `transpose()` function
+ Accessing the `T` attribute.

Execute the following code examples to see an example of an array transpose

In [94]:
# Create a 2 x 3 random matrix
demo_f = np.random.random((2,3))


print("The original matrix")
print(demo_f)

print("\nThe matrix after being tranposed")
print(np.transpose(demo_f))

print("\nThe tranposed matrix from the T attribute")
print(demo_f.T)


The original matrix
[[0.32418143 0.47398054 0.61982772]
 [0.645704   0.84503799 0.40664065]]

The matrix after being tranposed
[[0.32418143 0.645704  ]
 [0.47398054 0.84503799]
 [0.61982772 0.40664065]]

The tranposed matrix from the T attribute
[[0.32418143 0.645704  ]
 [0.47398054 0.84503799]
 [0.61982772 0.40664065]]


### 4.2 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create a matrix of any size and transpose it.

In [108]:
array = np.arange(1,26)
new = tarray.reshape(5,5)
tarray = np.transpose(new)
print(f"original: \n {array}, \n reshaped: \n {new},\n transposed: \n {tarray}")

original: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25], 
 reshaped: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]],
 transposed: 
 [[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


### 4.3 Reshaping and Resizing
You can change the dimensions of your array by use of the following two functions:
 + `resize()`
 + `reshape()`
 
The `resize()` function allows you to "stretch" your array to increase its size.  This can be useful if you need to add more data to an existing array or you need to adjust it prior to performing arithmatic and Broadcasting.

The `reshape()` function allows you to change the dimensions of an existing array. For example, if you have a _3 x 2_ array you can change it to a _6 x 1_ array using the `reshape()` function without losing the data values in the array.

Examine and execute the following code adapted from the DataCamp Tutorial:

In [4]:
# Create an array x of size 4 x 1. Print the shape of `x`
x = np.array([1,1,1,1])
print(x.shape)

# Resize `x` to ((6,4))
np.resize(x, (6,4))

(4,)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Notice how the array was resized from a _4 x 1_ to a _6 x 4_ array.

In [9]:
# Reshape `x` to (2,6)
x = np.array([1,2,3,4])
print("\noriginal:")
print(x)
print("\nreshaped:")
print(x.reshape((2,2)))


original:
[1 2 3 4]

reshaped:
[[1 2]
 [3 4]]


### 4.4 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [18]:
array = np.arange(2,9,2)
array
print(f"first array: \n{np.resize(array, (2,6))}")
array2 = np.zeros((8,2))
print(array2)
print(f"second array\n{np.resize(array2, (4,4))}")

first array: 
[[2 4 6 8 2 4]
 [6 8 2 4 6 8]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
second array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 4.5 Appending Arrays
Sometimes, you may want to want to append one array to another.  You can append one array to another using the `append()` function.  You can append an array to any dimension.  Remember that NumPy arrays have **axes**.  When you append one array to another you must specify the axes (e.g. row or column for 2D array) that you want to append. Axes are identified using a numeric index starting from 0, therefore:

+ `0`: the first dimension (the columns, or x-axis)
+ `1`: the second dimension (the rows, or y-axis)
+ `2`: the third dimension (the z-axis)
+ `3`: the fourth dimension
+ etc...

For example, examine and execute this code borrowed from the DataCamp tutorial:

In [19]:
# Append a 1D array to your `my_array`
my_array = np.array([1,2,3,4])
print(f"my_array \n{my_array}")
new_array = np.append(my_array, [7, 8, 9, 10])
print(f"new_array \n{new_array}")
# Print `new_array`


# Append an extra column to your `my_2d_array`
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print(f"my_2d_array \n{my_2d_array}")
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)
print(f"new_2d_array \n{new_2d_array}")



my_array 
[1 2 3 4]
new_array 
[ 1  2  3  4  7  8  9 10]
my_2d_array 
[[1 2 3 4]
 [5 6 7 8]]
new_2d_array 
[[1 2 3 4 7]
 [5 6 7 8 8]]


In the code above, for the first example, the array `[7, 8, 9, 10]` is appended or added to the existing 1D `my_array`.  For the second example, the values `7` and `8` are added to the rows (note the `axis=1` parameter.

In [32]:
#help(np.append)

### 4.6. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [43]:
array = np.array([[1,5,3,9], [5,6,8,9], [5,5,5,6]])
print(f"array \n{array}")

new_array = np.append(array, [[8],[9],[5]], axis=1)
print(f"new_array:\n {new_array}")

#print(f"append_array:" \n  {array.append([[8],[9],[5]]})

array 
[[1 5 3 9]
 [5 6 8 9]
 [5 5 5 6]]
new_array:
 [[1 5 3 9 8]
 [5 6 8 9 9]
 [5 5 5 6 5]]


### 4.7. Inserting and Deleting Elements
You can easily add a new element, or elements to an array using the `insert()` and `delete()` functions.  

In [51]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

### 4.8. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.


In [83]:
array =  np.arange(3,25,3)
array.shape =(2,4)
array
print(f"array:\n {array}")


new_array = np.insert(array, 2,(1,2,5,9), axis=0)
print(f"new_array:\n {new_array}")

new1_array = np.delete(new_array, 3, axis=1)
print(f"newest_array:\n {new1_array}")


array:
 [[ 3  6  9 12]
 [15 18 21 24]]
new_array:
 [[ 3  6  9 12]
 [15 18 21 24]
 [ 1  2  5  9]]
newest_array:
 [[ 3  6  9]
 [15 18 21]
 [ 1  2  5]]


### 4.9 Joining Arrays
There are a variety of functions for joining arrays:

 + `concatenate()`
 + `vstack()`
 + `hstack()`
 + `column_stack()`

Each of these functions is used in the following code borrowed from a [DataCamp](https://www.datacamp.com/) tutorial. Examine and execute the following code cell:

In [86]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


### 4.10. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Execute the code (as shown above).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question
  + Can you identify what is happening with each of them?

In [87]:
concatinate() joins both 1D arrays 
vstack() stacks rows  
hstack() stacks columns
column_stack() does the same as hstack

SyntaxError: invalid syntax (741534552.py, line 1)

### 4.11. Splitting an Array
You may find that you need to split arrays. The following functions allow you to split horizontally or vertically:
 + `vsplit()`
 + `hsplit()`
 
Examine and execute the following code borrowed from the DataCamp Tutorial:

In [90]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### 4.12. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Execute the code (as shown above).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question
  + Can you identify what is happening with each of them?

In [ ]:
vsplit() works from top to bottom  and slpits the rows into sperate arrays
hsplit() works from left to right and splits the columns into seperate arrays

## Expected Outcomes
At this point, you should feel comfortable with the following:
- Indexing and subsetting of arrays.
- "Fancy" indexing
- Tranposing arrays
- Reshaping arrays
- Inserting and deleting elements
- Joining arrays
- Splitting an array

## What to Turn in?
Be sure to **commit** and **push** your changes to this notebook.  All practice exercises should be completed.  Once completed, send a **Slack message** to the instructor indicating you have completed this assignment. The instructor will verify all work is completed. 